version: "2"
services:
  # Web Service
  www:
    image: orsolin/docker-php-5.3-apache
    container_name: web
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./grandadmin:/var/www/html/
    links:
      - db
    networks:
      - default
  # MySQL Service
  db:
    image: mysql:5.6.50
    container_name: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: remaining_budget
      MYSQL_USER: rembg
      MYSQL_PASSWORD: rembg9999
      MYSQL_ROOT_PASSWORD: root9999
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - ./docker/conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    networks:
      - default
  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db:db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: rembg
      MYSQL_PASSWORD: rembg9999
      MYSQL_ROOT_PASSWORD: root9999
volumes:
  persistent:
